/* eslint-disable */
/* global WebImporter */

/**
 * Transformer for WKND website cleanup
 * Purpose: Remove non-content elements (header, footer, navigation, tracking)
 * Applies to: wknd.site (all templates)
 * Tested: /us/en.html
 * Generated: 2026-02-25
 *
 * SELECTORS EXTRACTED FROM:
 * - Captured DOM during migration workflow (cleaned.html)
 */

const TransformHook = {
  beforeTransform: 'beforeTransform',
  afterTransform: 'afterTransform',
};

export default function transform(hookName, element, payload) {
  if (hookName === TransformHook.beforeTransform) {
    // Remove header experience fragment
    // EXTRACTED: Found <header class="experiencefragment cmp-experiencefragment--header">
    WebImporter.DOMUtils.remove(element, [
      'header.cmp-experiencefragment--header',
    ]);

    // Remove footer experience fragment
    // EXTRACTED: Found <footer class="experiencefragment cmp-experiencefragment--footer">
    WebImporter.DOMUtils.remove(element, [
      'footer.cmp-experiencefragment--footer',
    ]);

    // Remove mobile navigation toggle and menu
    // EXTRACTED: Found <div id="toggleNav"> and <div id="mobileNav" class="cmp-navigation--mobile">
    WebImporter.DOMUtils.remove(element, [
      '#toggleNav',
      '#mobileNav',
    ]);

    // Remove Adobe tracking iframe
    // EXTRACTED: Found <iframe id="destination_publishing_iframe_wkndsite_0" src="...demdex.net...">
    WebImporter.DOMUtils.remove(element, [
      'iframe[id^="destination_publishing_iframe"]',
    ]);

    // Remove carousel navigation controls (prev/next buttons and indicators)
    // These are generated by JS and not part of authored content
    // EXTRACTED: Found <div class="cmp-carousel__actions"> and <ol class="cmp-carousel__indicators">
    WebImporter.DOMUtils.remove(element, [
      '.cmp-carousel__actions',
      '.cmp-carousel__indicators',
    ]);
  }

  if (hookName === TransformHook.afterTransform) {
    // Remove any remaining iframes and noscript elements
    WebImporter.DOMUtils.remove(element, [
      'iframe',
      'noscript',
    ]);

    // Clean up meta elements left in image containers
    // EXTRACTED: Found orphan <meta> tags inside .cmp-image divs
    WebImporter.DOMUtils.remove(element, [
      '.cmp-image meta',
    ]);
  }
}
